
## Context like the following {data-video="small top-right"}

::: {.text-left}
[Quarto](https://quarto.org/) allows to:
:::

- Create slides in various formats like LaTeX, RevealJS, or PowerPoint
- Produce articles, dashboards, websites
- Write content in markdown and export nice interactive slideshows

::: {.fragment}
&rarr; Don't hesitate to look at the [documentation](https://quarto.org/docs/get-started/) to get started.
:::


## Plugins and integrated tools

::: {.text-left}
You can automatically deploy you slides online using CI/CD and make use of integrated tools like:
:::


- Slides overview: type "o"
- Speaker notes view with "S"
- Excalidraw (plugin): A drawing tool -> type "x" to go to the white board
- Pointers (plugin): type "p" to show a red pointer
- Simply type "?" to learn more about RevealJS navigation


::: {.fragment}
&rarr; Look at the [documentation](https://quarto.org/docs/presentations/) to learn more!
:::

## Callouts for nice blocks 


::: {.columns}
::: {.column width="50%"}
::: {.callout-tip title="Hi there!"}
This is a cool callout-tip !
:::

::: {.callout-note title="Hi there!"}
This is a cool callout-note !
:::

::: {.callout-warning title="Hi there!"}
This is a cool callout-warning !
:::

:::

::: {.column width="50%"}

::: {.callout-important title="Hi there!"}
This is a cool callout-important !
:::
::: {.callout-caution title="Hi there!"}
This is a cool callout-caution !
:::
:::
:::
