name: Deploy Quarto Reveal.js Slides with Custom Docker Image

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pgalmiche0/defense-presentation-quarto:v1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Render Quarto slides
        working-directory: ./quarto
        run: quarto render index.qmd --to revealjs

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: quarto/_output

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
